// public class BasicJavaTest {
//     public static void main(String[] args){
//         int[] initArray = {};
//         BasicJava iD = new BasicJava();
//         System.out.println(iD.oddArray(initArray));
//     }
// }

// public class BasicJavaTest {
//     public static void main(String[] args){
//         int[] initArray = {-3,-5,1,3,5,7,9,4,13};
//         BasicJava iD = new BasicJava();
        
//         System.out.println(iD.MinMaxAvg(initArray));
//     }
// }

public class BasicJavaTest {
    public static void main(String[] args){
        int[] initArray = {-3,-5,1,3,5,7,9,4,13};
        BasicJava iD = new BasicJava();
        
        System.out.println(iD.shiftVal(initArray));
    }
}